---
- name: Hello Ansible from Packer
  hosts: localhost
  become: yes
  become_method: sudo
    
  tasks:
  - name: create a random password
    ansible.builtin.set_fact:
      password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=8) }}"
  
  - name: Set password for {{ ansible_env.SUDO_USER }}
    ansible.builtin.user:
      name: "ubuntu"
      password: "{{ password | password_hash('sha512') }}"
    become: yes
      
  - name: Run PHP command to get version
    command: php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;"
    register: php_version
    changed_when: false

  - name: Update packages
    apt:
      update_cache: yes
      upgrade: dist